# Generated by Django 2.0 on 2017-12-26 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PicType', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PicInfo',
            new_name='Pic',
        ),
    ]
