# Generated by Django 2.0 on 2017-12-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PicType', '0002_auto_20171226_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pic',
            old_name='picType',
            new_name='picNumType',
        ),
        migrations.AddField(
            model_name='pic',
            name='picTypeName',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
