# Generated by Django 2.0 on 2017-12-26 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PicType', '0003_auto_20171226_1106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pic',
        ),
    ]
